resolver: lts-21.25  # GHC 9.4.8

packages:
  - .
  - medicus-api

# Extra dependencies
extra-deps:
  - morpheus-graphql-0.27.3
  - morpheus-graphql-app-0.27.3
  - morpheus-graphql-core-0.27.3
  - morpheus-graphql-server-0.27.3
  - morpheus-graphql-subscriptions-0.27.3
  - relude-1.2.1.0
  - deriving-aeson-0.2.9

# Allow newer versions
allow-newer: true

# System dependencies
system-ghc: false
install-ghc: true

# Build options
ghc-options:
  "$locals": -Wall -Wcompat -fno-warn-orphans
